### ISSUE TITLE
Add logic in options.ts to handle API key submission

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#15]
## Proposed changes

Right now, we're asking for the API key in `popup.ts`, but it would be a better user experience if we had an options page that allows the user to put in their Deepgram API key and iTranslate (eventually) at the same time. 

Take a look at `options.html` to see the input and form information. 

Move the logic out of `popup.ts` to `options.ts`

**Comment by rmirville** [comment]
@BekahHW What should the extension look like when this is done? Would a PR for this include adding an options button/link to `popup.html` and a "Save Settings" button/link on `options.html` that takes you back?

**Comment by BekahHW** [comment]
@rmirville options is a special case for chrome extensions. This blogpost has images that shows where the options will populate once added to the manifest.json file. 

https://medium.com/extensions-development/chrome-extension-options-page-9428920f7309

**Comment by rmirville** [comment]
Okay, great. I'd like to work on this issue!

**Comment by BekahHW** [comment]
Absolutely, @rmirville!
