### ISSUE TITLE
Add Styling to popup

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#2]
In `popup.html`, add a `style` element inside the `head` section. 

- Create a wider body for the popup.
- Set the width of the buttons and display them in the same row. (In total, we'll have four buttons: start, stop, clear, and translate)
- Add style to the paragraph element where the transcript appears. Consider line-height, text size, and padding. 

For more information and an example, check out the "Internal CSS" section of ["CSS How To"](https://www.w3schools.com/css/css_howto.asp) from W3 schools.

**Comment by rmirville** [comment]
I'd like to tackle this issue! Can you assign it to me?

**Comment by BekahHW** [comment]
It's all you, @rmirville! Let me know if you need any help.

**Comment by rmirville** [comment]
@BekahHW I have a couple questions:

1. Do you want the PR to include adding the clear and translate buttons?
2. Does the `button-name` attribute on Start need to be added to the other buttons, too?
https://github.com/deepgram-devs/dg-translation-chrome-ext/blob/c3b33c38f5f0d30ba02d394fe10156badabda1be/src/popup.html#L10

**Comment by BekahHW** [comment]
1. Let's leave those off for now. 
2. Go ahead and add that on.
