### ISSUE TITLE
Add form for Feature Request

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#20]
## Template -> Form
We are currently using templates for Feature Requests. Let's make this a better user experience by turning the template into a form.

### Process
- To create a form, you need to make a .yml file. We'll call it `feature_request.yml`. 
- Using the same questions included in the template, update the current .md file. Take a look at [bug_report.yml](https://github.com/deepgram-devs/dg-translation-chrome-ext/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) as an example. In fact, everything from `- type: dropdown id: browsers` can be copied and pasted into the form. 
- If you have questions about what type of field for the top portion, please reach out.

**Comment by abuna1985** [comment]
Can i work on this one @BekahHW?

**Comment by BekahHW** [comment]
Absolutely, @abuna1985!

**Comment by abuna1985** [comment]
@BekahHWI currently have the first 2 sections (Proposed Changes, Context) required within the `feature_request.yml` file. Is this correct?

**Comment by BekahHW** [comment]
@abuna1985 that looks good!

**Comment by abuna1985** [comment]
@BekahHW Cool. Would you like me to remove `feature_request.md`?

**Comment by BekahHW** [comment]
@abuna1985 yes please.
