### ISSUE TITLE
Remove API input in popup

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#27]
Initially, we had an API input in the popup for the user to add their key. Now that we have the options page that allows the user to save it, we don't need to include it. 

What we could have instead, is a link to the options page.

For this issue, remove the input and associated button with the API. Add a link to the options page with the message "If you haven't already, add and save your API key here."

**Comment by arndom** [comment]
@BekahHW can I be assigned this as well?

**Comment by BekahHW** [comment]
@arndom absolutely!
