### ISSUE TITLE
Style options page

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#28]
To see the options page, load the extension unpacked in the browser. If you have the extension pinned to your browser, you can right-click and select `Options.` 

The about the section could be broken down for readability and to look better.

**Comment by arndom** [comment]
Hey @BekahHW, Can I be assigned this?

**Comment by BekahHW** [comment]
It's all you, @arndom!

**Comment by arndom** [comment]
the options are currently in a popup, should that be maintained?

**Comment by BekahHW** [comment]
Hey @arndom! Thanks for all your work on this. For some reason, I wasn't getting notifications for this repo.
