### ISSUE TITLE
Add toggle for password visibility

### ISSUE THREAD

**Issue by BekahHW** [deepgram-devs/dg-translation-chrome-ext#8]
When the user pastes in their API key, it's currently visible on the screen. Let's create a toggle that allows them to choose whether or not to make the API key visible. 

[This blog post](https://www.javascripttutorial.net/javascript-dom/javascript-toggle-password-visibility/) might be helpful.

**Comment by aishwarya-mali** [comment]
@BekahHW Can I work on this?

**Comment by BekahHW** [comment]
@aishwarya-mali yes! Let me know if you have any questions.
